package ru.raspberry.launcher.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object AppColorSchemes {
    val Light = lightColorScheme(
        primary = Color(0xFF8E4955),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DD),
        onPrimaryContainer = Color(0xFF72333E),
        inversePrimary = Color(0xFFFFB2BC),
        secondary = Color(0xFF76565A),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9DD),
        onSecondaryContainer = Color(0xFF5C3F43),
        tertiary = Color(0xFF795831),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDDB9),
        onTertiaryContainer = Color(0xFF5E411C),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF22191A),
        surfaceVariant = Color(0xFFF3DDDF),
        onSurfaceVariant = Color(0xFF524345),
        outline = Color(0xFF847374),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFEEDED),
        surfaceTint = Color(0xFF8E4955),
        outlineVariant = Color(0xFFD7C1C3),
        scrim = Color(0xFF000000)
    )

    val LightMediumContrast = lightColorScheme(
        primary = Color(0xFF5D222E),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFA05863),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFFB2BC),
        secondary = Color(0xFF4A2F33),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF856569),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF4B310D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF89673E),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF740006),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFCF2C27),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF170F10),
        surfaceVariant = Color(0xFFF3DDDF),
        onSurfaceVariant = Color(0xFF403334),
        outline = Color(0xFF5E4F50),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFEEDED),
        surfaceTint = Color(0xFF8E4955),
        outlineVariant = Color(0xFF7A696A),
        scrim = Color(0xFF000000)
    )

    val LightHighContrast = lightColorScheme(
        primary = Color(0xFF501824),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF753540),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFFB2BC),
        secondary = Color(0xFF3E2529),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF5F4145),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF402704),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF61431E),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF600004),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF98000A),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFF3DDDF),
        onSurfaceVariant = Color(0xFF000000),
        outline = Color(0xFF36292A),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFFFFFF),
        surfaceTint = Color(0xFF8E4955),
        outlineVariant = Color(0xFF544547),
        scrim = Color(0xFF000000)
    )

    val Dark = darkColorScheme(
        primary = Color(0xFFFFB2BC),
        onPrimary = Color(0xFF561D28),
        primaryContainer = Color(0xFF72333E),
        onPrimaryContainer = Color(0xFFFFD9DD),
        inversePrimary = Color(0xFF8E4955),
        secondary = Color(0xFFE5BDC1),
        onSecondary = Color(0xFF43292D),
        secondaryContainer = Color(0xFF5C3F43),
        onSecondaryContainer = Color(0xFFFFD9DD),
        tertiary = Color(0xFFEABF8F),
        onTertiary = Color(0xFF452B07),
        tertiaryContainer = Color(0xFF5E411C),
        onTertiaryContainer = Color(0xFFFFDDB9),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDF),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFF0DEDF),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFD7C1C3),
        outline = Color(0xFF9F8C8E),
        inverseSurface = Color(0xFFF0DEDF),
        inverseOnSurface = Color(0xFF382E2F),
        surfaceTint = Color(0xFFFFB2BC),
        outlineVariant = Color(0xFF524345),
        scrim = Color(0xFF000000)
    )

    val DarkMediumContrast = darkColorScheme(
        primary = Color(0xFFFFD1D6),
        onPrimary = Color(0xFF48121E),
        primaryContainer = Color(0xFFC97A86),
        onPrimaryContainer = Color(0xFF000000),
        inversePrimary = Color(0xFF73343F),
        secondary = Color(0xFFFCD2D6),
        onSecondary = Color(0xFF371F22),
        secondaryContainer = Color(0xFFAC888C),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFFFD5A7),
        onTertiary = Color(0xFF382000),
        tertiaryContainer = Color(0xFFB08A5E),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFFFD2CC),
        onError = Color(0xFF540003),
        errorContainer = Color(0xFFFF5449),
        onErrorContainer = Color(0xFF000000),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDF),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFEDD7D9),
        outline = Color(0xFFC1ADAF),
        inverseSurface = Color(0xFFF0DEDF),
        inverseOnSurface = Color(0xFF312829),
        surfaceTint = Color(0xFFFFB2BC),
        outlineVariant = Color(0xFF9E8C8D),
        scrim = Color(0xFF000000)
    )

    val DarkHighContrast = darkColorScheme(
        primary = Color(0xFFFFEBED),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFFFACB8),
        onPrimaryContainer = Color(0xFF210006),
        inversePrimary = Color(0xFF73343F),
        secondary = Color(0xFFFFEBED),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFFE1B9BD),
        onSecondaryContainer = Color(0xFF190609),
        tertiary = Color(0xFFFFEDDD),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFFD1AA7D),
        onTertiaryContainer = Color(0xFF231300),
        error = Color(0xFFFFEFEE),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFFFF5449),
        onErrorContainer = Color(0xFF000000),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDF),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFFFFFFF),
        outline = Color(0xFFD3C1C3),
        inverseSurface = Color(0xFFF0DEDF),
        inverseOnSurface = Color(0xFF000000),
        surfaceTint = Color(0xFFFFB2BC),
        outlineVariant = Color(0xFFD3C1C3),
        scrim = Color(0xFF000000)
    )
}