name: Build Native Distributions

on:
  workflow_dispatch:

jobs:
  build-pkg:
    name: Build .pkg (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create tokens.yaml from secret
        run: |
          printf '%s\n' "${{ secrets.TOKENS_YAML }}" > tokens.yaml
          chmod 600 tokens.yaml

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build .pkg
        run: ./gradlew packageReleasePkg

      - name: Upload debug .pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-launcher-pkg
          path: ./composeApp/build/compose/binaries/main/pkg/*.pkg

      - name: Upload release .pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-launcher-pkg
          path: ./composeApp/build/compose/binaries/main-release/pkg/*.pkg

  build-deb:
    name: Build .deb (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create tokens.yaml from secret
        run: |
          printf '%s\n' "${{ secrets.TOKENS_YAML }}" > tokens.yaml
          chmod 600 tokens.yaml

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build .deb
        run: ./gradlew packageReleaseDeb

      - name: Upload debug .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-launcher-deb
          path: ./composeApp/build/compose/binaries/main/deb/*.deb

      - name: Upload release .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-launcher-deb
          path: ./composeApp/build/compose/binaries/main-release/deb/*.deb

  build-msi:
    name: Build .msi (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create tokens.yaml from secret (Windows)
        shell: pwsh
        run: |
          $content = "${{ secrets.TOKENS_YAML }}"
          Set-Content -Path tokens.yaml -Value $content -NoNewline

      - name: Build .msi
        run: ./gradlew packageReleaseMsi

      - name: Upload debug .msi artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-launcher-msi
          path: ./composeApp/build/compose/binaries/main/msi/*.msi

      - name: Upload release .msi artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-launcher-msi
          path: ./composeApp/build/compose/binaries/main-release/msi/*.msi
